# Generated by Django 3.2.3 on 2021-05-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='value',
            new_name='total',
        ),
    ]
